### PR TITLE
Using pairwise deletion when calculating distance matrix

### PR DESCRIPTION
**Pull request by MVesuviusC**
I changed the dist.dna function to calculate pairwise deletions by default to fix an issue where very divergent sequences retrieved from blast can result in an empty distance matrix and a tree with zero tips. ex: plot(search_primer_pair(name="Archaea 16S","CCGACGGTGAGRGRYGAA","GTGCTCCCCCGCCAATTCCT",num_aligns=1000))

### CODE REVIEW

**Comment by jimhester** [comment]
This change makes it impossible to change the default from pairwise.deletion if you wanted to however.

If you want pairwise.deletion to be the default you should add it as an argument to `tree_from_alignment` with a default value of `TRUE` and then pass that value to the dist.dna function.

``` r
 tree_from_alignment = function(dna, pairwise.deletion = TRUE, ...) {
   nj(dist.dna(dna, model="N", pairwise.deletion = pairwise.deletion, ...))
 }
```

You will have to document the new pairwise.deletion argument and re-oxygenize as well.  (See http://r-pkgs.had.co.nz/man.html#man-workflow if you are unsure how to do this).

**Comment by MVesuviusC** [comment]
Ok, I think I did that all properly. Let me know if I mixed anything up. It looks like the documentation is in order now.

**Comment by jimhester** [comment]
Hmm, it looks like you are using a very old version of roxygen2, could you run `sessionInfo()` and see what version you have installed?  Preferably at least 4.0.  If versions that new are not available for your R version let me know and I can just run it myself.

**Comment by MVesuviusC** [comment]
I'm using whiskey to make changes on, so most of the packages are somewhat old. I had roxygen2_3.0.0. I upgraded it to 4.1.0 and reoxygenated everything.

**Comment by jimhester** [comment]
Ok looks good, thanks!

**Pull request merged**
