### PR TITLE
Fix ncbi rate limit issue

### PR DESCRIPTION
**Pull request by MVesuviusC**
Jim, 

Since I'm at a university I am running into rate limit issues accessing NCBI's servers. See:
[https://github.com/jimhester/primerTree/issues/35](https://github.com/jimhester/primerTree/issues/35)
and
[https://github.com/jimhester/primerTree/issues/33](https://github.com/jimhester/primerTree/issues/33)
NCBI recently implemented access limits to their e-utilities servers of 3 requests per second. You can get an api key as explained [here](https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/). If you have an api key you can get bumped up to 10 requests per second.

This is an issue for primerTree because we are downloading specific portions of the sequences identified by primerBlast as amplifiable by the input primers. These queries need to be performed one at a time because we specify the start and stop positions of the requested sequence. This can exceed the rate limit, especially if you are at a site such as a university where many users can share the IP address that NCBI uses to identify users for rate limiting. 

To overcome this, I re-coded the sequence query request to limit the number of queries performed. I also created a new input option "api_key" that allows the user to provide an api key so that primerTree can increase the query rate to 10 per second. I also included a pause in the retry_post function because a behavior I observed in testing was that if the NCBI query didn't respond quickly enough the retry function would hit the server with five requests in quick succession, hitting the rate limit. By telling it to pause for a brief period this problem is avoided and since this doesn't happen often it doesn't add much analysis time. 

Let me know how the code looks and any changes you'd like. 

Matt

### CODE REVIEW

**Comment by jimhester** [comment]
Rather than passing the key just as a normal argument you could instead read it from an environment variable, say `NCBI_API_KEY` or similar. 

This way you can set it in your `.Renviron` or shell dotfiles and not have they key exposed in your scripts or command history. 

You can retrieve the environment variable from R with `Sys.getenv()`. If you want to provide both the api_key argument and read it from the environment do something like `api_key = Sys.getenv("NCBI_API_KEY")` then check for `nzchar(api_key)` in the code.

**Comment by MVesuviusC** [comment]
Thanks Jim, that's a good idea. I'd worried about publishing anything using primerTree and forgetting to go in and manually delete my api key in the pipeline. I'll let you know when I get that working.

**Comment by jimhester** [comment]
Thanks!

**Comment by MVesuviusC** [comment]
Thanks Jim, sorry for not circling back to include the Sys.getenv() change.

**Pull request merged**
